
server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: ternscode-api-gateway
  cloud:
    gateway:
      routes:
        - id: ternscode-user-service
          uri: lb://ternscode-user-service
          predicates:
            - Path=/user/**
        - id: terncsode-contact-service
          uri: lb://ternscode-contact-service
          predicates:
            - Path=/contact/**
